### PR TITLE
Isn't 0.4 really working?

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[ci skip]

### CODE REVIEW

**Comment by stevengj** [comment]
Should be 0.4 and 0.5 lines, not `release`.

**Comment by stevengj** [comment]
This should not have been a ci skip PR, since it changes the test script.

**Comment by PallHaraldsson** [comment]
Right.. I see it immediately when you mention it.. Just had gotten in that habit (mostly doc changes, and this really isn't).

Is this not merged because of it (as "This branch has no conflicts with the base branch", would be false..)?

**Comment by stevengj** [comment]
I don't want to merge a change to the testing scripts without actually running the tests.

**Comment by tkelman** [comment]
Was also an exact duplicate of https://github.com/stevengj/DecFP.jl/pull/27, and was made redundant by a commit pushed straight to master.

**Pull request closed without merging**
