### PR TITLE
Fix OS_NAME dep warn

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by quinnj** [comment]
Thanks! I've been meaning to do this for a while.

**Comment by ranjanan** [comment]
Sure, would you mind tagging a new release please?

**Comment by ranjanan** [comment]
@quinnj Bump, could you tag a new release please?

**Comment by tkelman** [comment]
Master is failing tests. That should be fixed first.

**Comment by ranjanan** [comment]
> Master is failing tests. 

It seems that right now, the URL from which the binary is being downloaded is down. But this happens only on Windows, I was able to download and get tests to pass on Mac just now. 

Or are you referring to #28?

**Comment by tkelman** [comment]
Both 0.5 builds at https://travis-ci.org/stevengj/DecFP.jl froze, or timed out. Is that a performance regression or a failure?

**Comment by ranjanan** [comment]
Is it possible to restart that build and see if it happens again?

**Comment by tkelman** [comment]
Only someone with commit access can do that. Or we could open a dummy trivial PR just to trigger Travis.

**Comment by tkelman** [comment]
or let's see if reopening https://github.com/stevengj/DecFP.jl/pull/27 causes it to re-trigger

**Comment by ranjanan** [comment]
It certainly looks like only 0.5 is freezing on Travis, but I'm not able to reproduce this on JuliaBox or another GCE instance.

**Pull request merged**
